<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>bin</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>False</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaXamlIlDebuggerLaunch>False</AvaloniaXamlIlDebuggerLaunch>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ReSplit.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <PluginOutputDir>$(ProjectDir)../../../../ReSplit/bin/$(Configuration)/net10.0/Plugins/</PluginOutputDir>
    </PropertyGroup>

    <ItemGroup>
      <BuiltFiles Include="$(TargetDir)$(TargetName).*" />
    </ItemGroup>

    <MakeDir Directories="$(PluginOutputDir)" />
    <Copy SourceFiles="@(BuiltFiles)"
          DestinationFolder="$(PluginOutputDir)"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
