<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>bin</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>False</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaXamlIlDebuggerLaunch>False</AvaloniaXamlIlDebuggerLaunch>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ReSplit.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\..\..\..\ReSplit\bin\$(Configuration)\net10.0\Plugins\&quot; 2&gt;nul&#xD;&#xA;copy /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(ProjectDir)..\..\..\..\ReSplit\bin\$(Configuration)\net10.0\Plugins\&quot;" />
  </Target>

</Project>
